/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#1677FF',
        'primary-container': '#006ef2',
        'primary-fixed': '#d9e2ff',
        'primary-fixed-dim': '#afc6ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#fefcff',
        'on-primary-fixed': '#001a43',
        'on-primary-fixed-variant': '#004398',
        'inverse-primary': '#afc6ff',
        'surface-tint': '#0059c7',

        secondary: '#5d5f5f',
        'secondary-container': '#dfe0e0',
        'secondary-fixed': '#e2e2e2',
        'secondary-fixed-dim': '#c6c6c7',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#616363',
        'on-secondary-fixed': '#1a1c1c',
        'on-secondary-fixed-variant': '#454747',

        tertiary: '#9e3d00',
        'tertiary-container': '#c64f00',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb695',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7c2e00',

        error: '#FF4D4F',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        success: '#52C41A',
        warning: '#FAAD14',

        background: '#f7f9fc',
        'on-background': '#191c1e',
        surface: '#f7f9fc',
        'surface-dim': '#d8dadd',
        'surface-bright': '#f7f9fc',
        'surface-variant': '#e0e3e6',
        'surface-container': '#eceef1',
        'surface-container-low': '#f2f4f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e6e8eb',
        'surface-container-highest': '#e0e3e6',
        'on-surface': '#191c1e',
        'on-surface-variant': '#414755',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f4',

        outline: '#727786',
        'outline-variant': '#c1c6d7',
        'border-base': '#D9D9D9',
        divider: '#F0F0F0',

        'text-main': 'rgba(0,0,0,0.88)',
        'text-secondary': 'rgba(0,0,0,0.45)',

        // Ant Design Pro 页面底色
        page: '#F0F2F5',
      },
      borderRadius: {
        DEFAULT: '2px',
        lg: '4px',
        xl: '8px',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '16px',
        'container-margin': '24px',
      },
      fontFamily: {
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'title-base': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
        'data-tabular': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '20px', fontWeight: '400' }],
        'body-base': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'data-tabular': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'title-base': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['30px', { lineHeight: '38px', fontWeight: '600' }],
      },
      boxShadow: {
        'pro-card': '0 1px 2px rgba(0,0,0,.03), 0 1px 6px -1px rgba(0,0,0,.02)',
        'pro-card-hover': '0 4px 12px rgba(0,0,0,.05)',
        'pro-nav': '0 1px 2px rgba(0,0,0,.03)',
      },
    },
  },
  plugins: [],
  corePlugins: {
    // 让 Element Plus 的 preflight 与 Tailwind 兼容：不强制清 h1/h2 样式
    preflight: true,
  },
}
